### ISSUE TITLE
AbelMap doesn't evaluate at places close to discriminant points

### ISSUE THREAD

**Issue by cswiercz** [abelfunctions/abelfunctions#115]
The following divisor arithmetic code results in an error message:

``` python
sage: from abelfunctions import RiemannSurface, AbelMap
sage: from abelfunctions.differentials import Differential
sage: R.<x,y> = QQ[]
sage: f = x**2*y**3 - x**4 + 1
sage: X = RiemannSurface(f)
sage: omega = X.holomorphic_differentials()
sage: # compute eta = omega[0] + omega[2] by using numerators
sage: C = eta.valuation_divisor()
sage: AbelMap(C)
Traceback (click to the left of this block for traceback)
...
TypeError: Illegal initializer for algebraic number
```

Looking at the traceback it seems that there is something going on in path construction with the places contained in the valuation divisor `eta`. Taking a closer look we see:

``` python
sage: for P in eta.places:
....:    print P
....:    print
(0.7648844336005847? + 0.3524715460317263?*I, -1.078388932636736? +
0.4969396651474526?*I)

(0.7648844336005847? - 0.3524715460317263?*I, -1.078388932636736? -
0.4969396651474526?*I)

(-0.1812324444698754? + 1.083954101317711?*I, 0.1500514907094848? +
0.8974603263733937?*I)

(t^-3, t^-2 + O(t^0))

(-0.1812324444698754? - 1.083954101317711?*I, 0.1500514907094848? -
0.8974603263733937?*I)

(-1.167303978261419?, 0.8566748838545029?)
```

I think the problem is that the third place shown above with x-projection equal to `-0.1812324444698754? + 1.083954101317711?*I` clearly lies within the bounding circle of the discriminant point `I`. Currently, Abelfunctions is only set up to integrate to places either
1. sufficiently far away from discriminant points or
2. points that are exactly equal to a discriminant point.

This might take quite a bit of reworking of `RiemannSurfacePathPuiseux` in order to do well. If `RiemannSurfacePathPuiseux` needs to be rewritten slightly then it might be a good time to take advantage of some of the (fast) numerical techniques used in [1]. This technique has the advantage that 
1. we don't even need (slow) Puiseux series to integrate inside the bounding circles and
2. it is "target agnostic" in the sense that the same algorithm is used for integrating to the discriminant place, itself, as well as any other place in the bounding circle.

> [1] Frauendiener, Klein _"Computational Approach to Compact Riemann Surfaces"_ [arXiv:1510.09063](http://arxiv.org/abs/1510.09063)

**Comment by cswiercz** [comment]
Adding @jupsal to the convo.

**Comment by cswiercz** [comment]
Also, here is the code for computing the example differential `eta`. It's messy since differential arithmetic is not written yet.

```python
sage: numer = omega[0].as_expression().numerator() + omega[2].as_expression().numerator()
sage: denom = omega[0].as_expression().denominator()
sage: eta = Differential(X, numer, denom)
```

**Comment by DisneyHogg** [comment]
I have found the same error when working with `RiemannSurfacePathPuiseux`. It comes down to an error in `abelfunctions.puiseux` as below:
```
import abelfunctions.puiseux as puiseux
R.<x,y> = QQ[]
f = y^2-x*(x^4-1)
alpha = (-0.204496929165702+0.16536419940365704j)
puiseux(f,alpha)
```
Within here, `puiseux` transforms `f` to the polynomial `galpha = y^2 - 0.2057132516702637 + 0.16568560611296274*I`, and then tries to calculate the roots, but in the ring `QQbar`. Namely `puiseux` runs 
```
betas = galpha.roots(ring=QQbar, multiplicities=False)
```
and it is the choice of ring that is causing the problem. `alpha` cannot be coerced to `QQ` or `QQbar` as is tried in `RiemannSurfacePathPuiseux` (where the variable is here called `target_point`). Is it necessary to have the ring specified as QQbar in the functionality of `puiseux`? 

Running the original code provided no longer throws an error on my machine (sage 8.9, python 3.7.3) so I don't know whether it is worth making this it's own issue.

**Comment by DisneyHogg** [comment]
As per https://ask.sagemath.org/question/40335/question-abour-numerical-coercions/ a possible change in `RiemannSurfacePathPuiseux` is to change `QQbar(target_point)` to `QQbar(QQ(real_part(target_point))+I*QQ(imag_part(target_point)))`
