### ISSUE TITLE
Lot of deprecations with sage-7.1

### ISSUE THREAD

**Issue by videlec** [abelfunctions/abelfunctions#118]
With the new release of Sage there are plenty of warnings related to deprecations. For examples

* [x] the module sage.rings.commutative_ring is deprecated and will be removed
* [x] the module sage.rings.integral_domain is deprecated and will be removed
* [ ]  DisplayFormatter._ipython_display_formatter_default is deprecated: use @default decorator instead.
* [x] Importing xgcd from here is deprecated. If you need to use it, please import it directly from sage.arith.all

**Comment by cswiercz** [comment]
Thanks for noticing. There were even some uncaught depreciations in Sage 6.10, I think.

**Comment by cswiercz** [comment]
Note to self: `sage.arith.all` is not defined in Sage Version <= 6.10. Just import `xgcd` from `sage.all`.

**Comment by cswiercz** [comment]
@videlec In my test suite (which now uses sage-7.1) I don't see a depreciation warning for `DisplayFormatter._ipython_display_formatter_default`. Do you know what part of Abelfunctions is reporting this?
