### ISSUE TITLE
doc is missing  renaming of directory

### ISSUE THREAD

**Issue by dimpase** [abelfunctions/abelfunctions#119]
The installation doc is not correct in assuming that you can just Download Zip, unzip it, and create spkg file. The problem is that then the name of the directory is wrong, appending '-master' at the end, and so the resulting spkg does not install. One should rename the directory first, before making the spkg file.

**Comment by cswiercz** [comment]
I'll admit that I was having trouble understanding the Sage spkg process. The instructions could be much clearer. (And correct.)

**Comment by dimpase** [comment]
Probably things got changes subtly during the move to the latest structure of packages.
Probably noone checked that the old-style packages packagings instructions are still 100% right.
Probably a name like abelfunctions-1.2.3 would still work, I don't know. The github default (?), branch name at the end, never worked. Needless to say, constructive feedback is most welcome.

**Comment by cswiercz** [comment]
Fixed by 18296d96b510895ae38f440b23890c4df9edfe5e.
