### ISSUE TITLE
Failed Build on Sage v7.3

### ISSUE THREAD

**Issue by levml** [abelfunctions/abelfunctions#135]
For which version of sage is this package installable? I just tried on version 7.2 and got some errors. I then updated to version 7.3 and got the same errors.

**Comment by cswiercz** [comment]
Could you post the output from the build?

**Comment by levml** [comment]
$ /Applications/SageMath-7.3.app/sage -p abelfunctions.spkg
abelfunctions
====================================================
Extracting package /sage/abelfunctions.spkg
-rw-r--r--  1 staff  272934 Aug 30 15:34 /sage/abelfunctions.spkg
Finished extraction
****************************************************
Host system:
Darwin local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
****************************************************
C compiler: gcc
C compiler version:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/Applications/SageMath-7.3.app/Contents/Resources/sage/local/libexec/gcc/x86_64-apple-darwin15.6.0/4.9.3/lto-wrapper
Target: x86_64-apple-darwin15.6.0
Configured with: ../src/configure --prefix=/Applications/SageMath-7.3.app/Contents/Resources/sage/local --with-local-prefix=/Applications/SageMath-7.3.app/Contents/Resources/sage/local --with-gmp=/Applications/SageMath-7.3.app/Contents/Resources/sage/local --with-mpfr=/Applications/SageMath-7.3.app/Contents/Resources/sage/local --with-mpc=/Applications/SageMath-7.3.app/Contents/Resources/sage/local --with-system-zlib --disable-multilib --disable-nls --enable-languages=c,c++,fortran --disable-libitm --with-build-config=bootstrap-debug --without-isl --without-cloog  
Thread model: posix
gcc version 4.9.3 (GCC) 
****************************************************
running build_ext
cythoning abelfunctions/complex_path.pyx to abelfunctions/complex_path.c
building 'abelfunctions.complex_path' extension
C compiler: gcc -fno-strict-aliasing -I/Users/buildslave-sage/slave/binary_pkg/build/source/SageMath/jc4b6yulaujayb9sr94ia88eourzeqip0oidma/local/var/tmp/sage/build/python2-2.7.10.p2/include -DNDEBUG -g -fwrapv -O3 -Wall -Wno-unused

creating build
creating build/temp.macosx-10.9-x86_64-2.7
creating build/temp.macosx-10.9-x86_64-2.7/abelfunctions
compile options: '-I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/include -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/include/python2.7 -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/python2.7/site-packages/numpy/core/include -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/python2.7/site-packages -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/python2.7/site-packages/sage/ext -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/python2.7/site-packages/numpy/core/include -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/include/python2.7 -c'
extra options: '-std=c99 -w'
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules _winreg, win32api or win32con are installed.
gcc: abelfunctions/complex_path.c
In file included from /Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/gcc/x86_64-apple-darwin15.6.0/4.9.3/include-fixed/syslimits.h:7:0,
                 from /Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/gcc/x86_64-apple-darwin15.6.0/4.9.3/include-fixed/limits.h:34,
                 from /Applications/SageMath-7.3.app/Contents/Resources/sage/local/include/python2.7/Python.h:19,
                 from abelfunctions/complex_path.c:4:
/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/gcc/x86_64-apple-darwin15.6.0/4.9.3/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
 #include_next <limits.h>  /* recurse down to the real one */
                                                             ^
compilation terminated.
In file included from /Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/gcc/x86_64-apple-darwin15.6.0/4.9.3/include-fixed/syslimits.h:7:0,
                 from /Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/gcc/x86_64-apple-darwin15.6.0/4.9.3/include-fixed/limits.h:34,
                 from /Applications/SageMath-7.3.app/Contents/Resources/sage/local/include/python2.7/Python.h:19,
                 from abelfunctions/complex_path.c:4:
/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/gcc/x86_64-apple-darwin15.6.0/4.9.3/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
 #include_next <limits.h>  /* recurse down to the real one */
                                                             ^
compilation terminated.
error: Command "gcc -fno-strict-aliasing -I/Users/buildslave-sage/slave/binary_pkg/build/source/SageMath/jc4b6yulaujayb9sr94ia88eourzeqip0oidma/local/var/tmp/sage/build/python2-2.7.10.p2/include -DNDEBUG -g -fwrapv -O3 -Wall -Wno-unused -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/include -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/include/python2.7 -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/python2.7/site-packages/numpy/core/include -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/python2.7/site-packages -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/python2.7/site-packages/sage/ext -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/python2.7/site-packages/numpy/core/include -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/include/python2.7 -c abelfunctions/complex_path.c -o build/temp.macosx-10.9-x86_64-2.7/abelfunctions/complex_path.o -std=c99 -w" failed with exit status 1
running install
running build
running build_py
creating build/lib.macosx-10.9-x86_64-2.7
creating build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/__init__.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/abelmap.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/complex_path_factory.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/differentials.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/divisor.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/homology.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/integralbasis.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/puiseux.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/puiseux_series_ring.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/riemann_constant_vector.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/riemann_surface.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/riemann_surface_path.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/riemann_surface_path_factory.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/singularities.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/skeleton.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/version.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
copying abelfunctions/ypath_factory.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions
creating build/lib.macosx-10.9-x86_64-2.7/abelfunctions/riemann_theta
copying abelfunctions/riemann_theta/__init__.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions/riemann_theta
creating build/lib.macosx-10.9-x86_64-2.7/abelfunctions/utilities
copying abelfunctions/utilities/__init__.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions/utilities
copying abelfunctions/utilities/permutations.py -> build/lib.macosx-10.9-x86_64-2.7/abelfunctions/utilities
running build_ext
skipping 'abelfunctions/complex_path.c' Cython extension (up-to-date)
building 'abelfunctions.complex_path' extension
C compiler: gcc -fno-strict-aliasing -I/Users/buildslave-sage/slave/binary_pkg/build/source/SageMath/jc4b6yulaujayb9sr94ia88eourzeqip0oidma/local/var/tmp/sage/build/python2-2.7.10.p2/include -DNDEBUG -g -fwrapv -O3 -Wall -Wno-unused

compile options: '-I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/include -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/include/python2.7 -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/python2.7/site-packages/numpy/core/include -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/python2.7/site-packages -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/python2.7/site-packages/sage/ext -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/python2.7/site-packages/numpy/core/include -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/include/python2.7 -c'
extra options: '-std=c99 -w'
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules _winreg, win32api or win32con are installed.
gcc: abelfunctions/complex_path.c
In file included from /Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/gcc/x86_64-apple-darwin15.6.0/4.9.3/include-fixed/syslimits.h:7:0,
                 from /Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/gcc/x86_64-apple-darwin15.6.0/4.9.3/include-fixed/limits.h:34,
                 from /Applications/SageMath-7.3.app/Contents/Resources/sage/local/include/python2.7/Python.h:19,
                 from abelfunctions/complex_path.c:4:
/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/gcc/x86_64-apple-darwin15.6.0/4.9.3/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
 #include_next <limits.h>  /* recurse down to the real one */
                                                             ^
compilation terminated.
In file included from /Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/gcc/x86_64-apple-darwin15.6.0/4.9.3/include-fixed/syslimits.h:7:0,
                 from /Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/gcc/x86_64-apple-darwin15.6.0/4.9.3/include-fixed/limits.h:34,
                 from /Applications/SageMath-7.3.app/Contents/Resources/sage/local/include/python2.7/Python.h:19,
                 from abelfunctions/complex_path.c:4:
/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/gcc/x86_64-apple-darwin15.6.0/4.9.3/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
 #include_next <limits.h>  /* recurse down to the real one */
                                                             ^
compilation terminated.
error: Command "gcc -fno-strict-aliasing -I/Users/buildslave-sage/slave/binary_pkg/build/source/SageMath/jc4b6yulaujayb9sr94ia88eourzeqip0oidma/local/var/tmp/sage/build/python2-2.7.10.p2/include -DNDEBUG -g -fwrapv -O3 -Wall -Wno-unused -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/include -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/include/python2.7 -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/python2.7/site-packages/numpy/core/include -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/python2.7/site-packages -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/python2.7/site-packages/sage/ext -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/lib/python2.7/site-packages/numpy/core/include -I/Applications/SageMath-7.3.app/Contents/Resources/sage/local/include/python2.7 -c abelfunctions/complex_path.c -o build/temp.macosx-10.9-x86_64-2.7/abelfunctions/complex_path.o -std=c99 -w" failed with exit status 1
Error installing Abelfunctions

real	0m4.890s
user	0m3.452s
sys	0m1.028s
************************************************************************
Error installing package abelfunctions
************************************************************************
Please email sage-devel (http://groups.google.com/group/sage-devel)
explaining the problem and including the relevant part of the log file
  /Applications/SageMath-7.3.app/Contents/Resources/sage/logs/pkgs/abelfunctions.log
Describe your computer, operating system, etc.
If you want to try to fix the problem yourself, *don't* just cd to
/Applications/SageMath-7.3.app/Contents/Resources/sage/local/var/tmp/sage/build/abelfunctions and type 'make' or whatever is appropriate.
Instead, the following commands setup all environment variables
correctly and load a subshell for you to debug the error:
  (cd '/Applications/SageMath-7.3.app/Contents/Resources/sage/local/var/tmp/sage/build/abelfunctions' && '/Applications/SageMath-7.3.app/Contents/Resources/sage/sage' --sh)
When you are done debugging, you can type "exit" to leave the subshell.
************************************************************************

**Comment by cswiercz** [comment]
@levml Various versions of Sage have behaved differently in the past and the best installation process seems to change every time. Try installing via the following technique.

1. Enter the top-level directory of the package.

    ```
    $ cd abelfunctions
    ```

2. Run

    ```
    $ sage setup.py install
    ```

Please post any errors you encounter. Also, as I mentioned in email correspondence, the installation method you used should work on Sage v~7.0.

**Comment by cswiercz** [comment]
See #137. Abelfunctions should now build on Sage v>=7.3.
