### ISSUE TITLE
Cycle construction causes code to hang

### ISSUE THREAD

**Issue by tolsonMDA** [abelfunctions/abelfunctions#145]
When running `X.c_cycles()` on a Riemann surface `X`, the code will occasionally hang indefinitely while continuing to consume 100% of the processor. However, if you issue a KeyboardInterrupt and immediately rerun the same jupyter cell, it will execute instantly.

It may be related to https://github.com/abelfunctions/abelfunctions/pull/143/commits/01d830a88ccc4415bdff3737dcd19b9a2e2a8377

**Comment by rparini** [comment]
Yes that seems like the same problem with comparing `sage.rings.qqbar.AlgebraicNumber` objects.    I've merged your pull request into mine so at least this instance of that problem will be fixed when that's merged.

**Comment by tolsonMDA** [comment]
I think this was addressed with the recent merge.
