### ISSUE TITLE
Riemann-Theta numerically unstable

### ISSUE THREAD

**Issue by oOoDKoOo** [abelfunctions/abelfunctions#159]
It seems to me that the abelfunction package does not calculate the Riemann-Theta function correctly over all parameter space (likely because it is implemented in a numerically unsafe way).

As a simple g=1 example take Q=10i and z=5i. Abelfunctions returns ~1 while Mathematica ~2.

It is clear that the result should be ~2 as one gets actually an additional 1 from the n=-1 term in the summation for this particular choice of Q and z, (z=Q/2), while all the remaining terms ->0. The RT implementation of the abelfunctions does not "see" that n^2+n = 0 at n=-1, thereby missing an additional +1.

 I guess the underlying reason is that the used algo to calculate the RT factorizes the terms in an e^~Q and e^~z contribution with not sufficient precision for Q large.

**Comment by cswiercz** [comment]
Thank you for finding this! I found your [openRT](https://github.com/RiemannAI/openRT) package. What improvements, in particular, have you made to the code assuming you fixed the issue in your own package?

**Comment by oOoDKoOo** [comment]
We did not fix the issue yet. 

Note that this is a rather general problem as it occurs for the imaginary part of the solution set

1/2 n^tQn+n^t z = 0

I think this comes from the split into the exponential part and oscillatory part. The former you do in python while the latter in .c . So the only solution I currently see is to move both parts to .c and then use either arbitrary precision arithmetic, or do not factor at all.  

As for our application performance is of utmost importance ( we are doing research on using the riemann-theta function for machine learning ), likely we will take a look into skipping the factorization ...

**Comment by rparini** [comment]
Just to say that mpmath gets the right answer in your example although unfortunately it only implements Jacobi (g=1 or elliptic) theta functions.
```Python
q = 10j
z = 5j

from abelfunctions import RiemannTheta
print RiemannTheta([z], [[q]]) # = 1 (should be ~2)

from mpmath import jtheta, pi
print jtheta(3, pi*z, exp(1j*pi*q)) # = 2
```

**Comment by rparini** [comment]
@oOoDKoOo This should now be fixed but do let us know if you find any more issues.
