### ISSUE TITLE
Travis CI tests disabled

### ISSUE THREAD

**Issue by rparini** [abelfunctions/abelfunctions#171]
Travis CI is not running the tests and says "This is not an active repository" when you go to https://travis-ci.org/abelfunctions/abelfunctions.

Please can one of the project owners (assigned) re-enable the tests on Travis.  I don't have sufficient permissions to do it myself.

**Comment by chualynn** [comment]
I just activated it, is it working now?

**Comment by rparini** [comment]
Yes it's working now, thanks!
