### ISSUE TITLE
Closure of travis-ci.org

### ISSUE THREAD

**Issue by rparini** [abelfunctions/abelfunctions#194]
travis-ci.org will be [shut down at the end of May 2021](https://blog.travis-ci.com/2021-05-07-orgshutdown) so tests will no longer run after this point.

I did start following the [migration documentation](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) and I have requested access for the travis-ci.com GitHub app but I do not have admin permissions to grant it so I could not implement the rest of the migration process.  

However, it seems that if we did migrate to travis-ci.com [the new billing structure](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) would give us only 1000 Linux build minutes in the free tier. After which someone would have to email TravisCI support to ask for more minutes or sign up for a paid plan.  There's some more discussion of this [here](https://github.com/zopefoundation/meta/issues/38).  So given it takes ~20 mins to run the tests and we currently test against 7 different versions of Sage, we will quickly run out of minutes after a few commits with our current build matrix.

I would therefore suggest migrating to GitHub Actions instead since:
- It's free for public repos
- We wouldn't be relying on an additional external service: code and CI all in the same place
- It still allows the build matrix that we use to test against different versions of Sage

Sage itself seems to be using GitHub Actions these days too: https://github.com/sagemath/sage/actions.  I may or may not need an admin to flick a switch to enable that.  If I don't get any feedback by the time travis-ci.org is killed, I will have a go at implementing GitHub Actions and see how far I can get.

**Comment by cswiercz** [comment]
@rparini I recommend GitHub Actions. I've had good experience with it in other repositories.

Also, I will figure out how to grant you admin privileges of this repository. Thanks for taking such ownership of this work! I wish I had the time to continue contributing to this work...

**Comment by cswiercz** [comment]
I just granted you "Maintain" privileges. Let me know if that's sufficient.

**Comment by rparini** [comment]
Thanks @cswiercz, I just committed the template Python test workflow here: https://github.com/abelfunctions/abelfunctions/pull/196/commits/15e7373166e6068a183d9a2fa3cd52dfaf128d8c and Actions did run it so I think we're good permissions wise.  I'll migrate the Travis tests to Actions in that branch over the next few weekends!
