### ISSUE TITLE
Installation under Sagemath 9.5 (Python 3.10.12)

### ISSUE THREAD

**Issue by wobau** [abelfunctions/abelfunctions#211]
Hello, 

the given installation methods for abelfunctions ( Sagemath 9.5 , Python 3.10.12) do not work.  Anybody got an idea?  

Sincerely

Wolfgang Bauhardt

**Comment by rparini** [comment]
Hi Wolfgang, could share the error you're encountering and which steps you're using to try and install? 

The master branch of this repo should work with sage 9.5 as we successfully test against it, though maybe something's gone wrong!

**Comment by wobau** [comment]
Dear Robert Parini,

Thank you for your quick response.

Attached the error expression.

With best regards

Wolfgang Bauhardt

Am 08.08.2023 19:01 schrieb Robert Parini:

**Comment by rparini** [comment]
Hi Wolfgang,
There's nothing attached. Unfortunately, I think GitHub will not forward email attachments. But if you reply through the github website then you should be able to attach a file (see [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files)) to your comment

**Comment by wobau** [comment]
Dear Robert Parini,

Thank you for your quick response.

Attached the error expression.

With best regards

Wolfgang Bauhardt

########################################################################################################################################

1. sudo apt-get install sagemath

Version 9.5 Python 3.10.12


#########################################################################################################################################################
2 pip install git+https://github.com/abelfunctions/abelfunctions

Defaulting to user installation because normal site-packages is not 
writeable
Collecting git+https://github.com/abelfunctions/abelfunctions
   Cloning https://github.com/abelfunctions/abelfunctions to 
/tmp/pip-req-build-yk0hqadc
   Running command git clone --filter=blob:none --quiet 
https://github.com/abelfunctions/abelfunctions 
/tmp/pip-req-build-yk0hqadc
   Resolved https://github.com/abelfunctions/abelfunctions to commit 
efaf57ba61b2168adca17184d4f0836655c1138b
   Preparing metadata (setup.py) ... error
   error: subprocess-exited-with-error

   × python setup.py egg_info did not run successfully.
   │ exit code: 1
   ╰─> [18 lines of output]
       Traceback (most recent call last):
         File "/tmp/pip-req-build-yk0hqadc/setup.py", line 39, in 
<module>
           SAGE_ROOT = os.environ['SAGE_ROOT']
         File "/usr/lib/python3.10/os.py", line 680, in __getitem__
           raise KeyError(key) from None
       KeyError: 'SAGE_ROOT'

       During handling of the above exception, another exception 
occurred:

       Traceback (most recent call last):
         File "<string>", line 2, in <module>
         File "<pip-setuptools-caller>", line 34, in <module>
         File "/tmp/pip-req-build-yk0hqadc/setup.py", line 41, in 
<module>
           raise EnvironmentError('abelfunctions must be built using 
Sage:\n\n'
       OSError: abelfunctions must be built using Sage:

           $ sage setup.py <args> <kwds>

       [end of output]

   note: This error originates from a subprocess, and is likely not a 
problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Note: you may need to restart the kernel to use updated packages.


#########################################################################################################################################

3. Running command git clone --filter=blob:none --quiet 
https://github.com/abelfunctions/abelfunctions 
/tmp/pip-req-build-yk0hqadc


/tmp/pip-req-build-yk0hqadc/./setup.py:24: DeprecationWarning: The 
distutils package is deprecated and slated for removal in Python 3.12. 
Use setuptools or check PEP 632 for potential alternatives
   from distutils.core import setup, Command
Traceback (most recent call last):
   File "/tmp/pip-req-build-yk0hqadc/./setup.py", line 39, in <module>
     SAGE_ROOT = os.environ['SAGE_ROOT']
   File "/usr/lib/python3.10/os.py", line 680, in __getitem__
     raise KeyError(key) from None
KeyError: 'SAGE_ROOT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
   File "/tmp/pip-req-build-yk0hqadc/./setup.py", line 41, in <module>
     raise EnvironmentError('abelfunctions must be built using Sage:\n\n'
OSError: abelfunctions must be built using Sage:

         $ sage setup.py <args> <kwds>



Am 08.08.2023 19:01 schrieb Robert Parini:

**Comment by rparini** [comment]
So I think `SAGE_ROOT` should be set automatically if running with sage but maybe that's different for different distributions. Could you try
```
sage --pip install git+https://github.com/abelfunctions/abelfunctions
```
to ensure that you're installing against the bundled Sage Python, rather than your system Python?

If that doesn't work could you try the alternate method documented [here](https://github.com/abelfunctions/abelfunctions/blob/master/doc/Installation.md#alternate-method) (essentially cloning the repository and running `sage setup.py install`) at let me know what happens.

**Comment by wobau** [comment]
Dear Robert Parini,

also alternative installation methods (conda) did not work.

Since I really need your abelfunctions library, I set up a virtual 
machine with Ubuntu 20.04 and sagemath 9.0 and it works! Thank God!

Without abelfunctions I could not continue my paper on certain solutions 
of nonlinear wave equations: their software is fast and of high 
numerical accuracy.

With best regards

Wolfgang Bauhardt

Am 12.08.2023 14:59 schrieb Robert Parini:

**Comment by rparini** [comment]
Hi Wolfgang,
Glad you found a workaround, though not ideal to need a whole VM just for sage!

The problem you had with installing on the apt distribution of sage should be fixed by https://github.com/abelfunctions/abelfunctions/pull/219 so I'll close this issue but feel free to reply if you still have problems

Incidentally, I think to get sage and abelfunctions working with conda you actually need mamba, that's the method we use in our tests. So I think would be:
```sh
conda config --add channels conda-forge
conda install mamba -y
$CONDA/bin/mamba create -n sage sage=9.5 -y
$CONDA/bin/mamba run -n sage sage --pip install git+https://github.com/abelfunctions/abelfunctions
```
