### ISSUE TITLE
Riemann Matrix 

### ISSUE THREAD

**Issue by sharondavid0** [abelfunctions/abelfunctions#250]
Hi! Every time I try to run the code from the getting started page:
sage: from abelfunctions import *
sage: R.<x,y> = QQ[]
sage: X = RiemannSurface(y**3 + 2*x**3*y - x**7)
sage: X.riemann_matrix()

I get the following error on X.riemann_matrix() - "quad() got an unexpected keyword argument 'complex_func' "

Can someone help me out here? Thanks!

**Comment by rparini** [comment]
Hi @sharondavid0 I suspect you are running an old version of scipy. To confirm, could you run in sage
```
import scipy; scipy.__version__
import sage.misc.banner; sage.misc.banner.banner()
```
and post the output?

**Comment by sharondavid0** [comment]
Hi! So this is what I get:
scipy version: '1.8.0' 

SageMath version 9.5, Release Date: 2022-01-30            
Using Python 3.10.12. Type "help()" for help.

**Comment by rparini** [comment]
Thanks, I think this will be fixed by upgrading scipy which you can do by running:
```
sage -pip install scipy -U
```
Can you try that and let me know if that lets you run the readme example?

**Comment by rparini** [comment]
I've updated abelfunctions now so that it will require a compatible version of scipy so will close this issue. Let me know if you 're still having problems.
