### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by sharondavid0** [abelfunctions/abelfunctions#264]
Hello! I've been having some trouble installing abelfunctions and I'm not sure whether it's a sagemath issue or something else. I get the following  error every time I try to install it, but I've checked and numpy is installed. Thanks for your help!

Collecting git+https://github.com/abelfunctions/abelfunctions
  Cloning https://github.com/abelfunctions/abelfunctions to /private/var/folders/tn/mvj6xvhx7b54k57dq0n1j6ym0000gn/T/pip-req-build-1rk53x0v
  Running command git clone --filter=blob:none --quiet https://github.com/abelfunctions/abelfunctions /private/var/folders/tn/mvj6xvhx7b54k57dq0n1j6ym0000gn/T/pip-req-build-1rk53x0v
  Resolved https://github.com/abelfunctions/abelfunctions to commit 7b279c39fe4dec75f90482a24eb0bb9de47e80d4
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/opt/miniconda3/envs/sage/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/miniconda3/envs/sage/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/miniconda3/envs/sage/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/tn/mvj6xvhx7b54k57dq0n1j6ym0000gn/T/pip-build-env-51rupmvs/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/private/var/folders/tn/mvj6xvhx7b54k57dq0n1j6ym0000gn/T/pip-build-env-51rupmvs/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/tn/mvj6xvhx7b54k57dq0n1j6ym0000gn/T/pip-build-env-51rupmvs/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/tn/mvj6xvhx7b54k57dq0n1j6ym0000gn/T/pip-build-env-51rupmvs/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 25, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by rparini** [comment]
Could you try running 
```
sage -c "import numpy; print(numpy.__version__)"
```
just to double check you have numpy installed within sage. If this also errors with `No module named 'numpy'` then you need to `sage -pip install numpy`

**Comment by sharondavid0** [comment]
Hi, when I run the numpy version command, I get 1.26.4, so it's clearly installed. I think it might be a problem with sage dependencies or something. I've tried installing it all three ways and I get either the same error or a Call patterns error.
Thanks for your help.

**Comment by thierry-martinez** [comment]
This issue seems to be related to recent versions of `pip` and possibly `sage`.

I encountered the same error as @sharondavid0, which I was able to work around by using the option:
```
sage -pip install --no-build-isolation
```

Afterward, I ran into additional errors related to `lll_reduce`, `finite_sum_without_derivatives`, and `finite_sum_with_derivatives` being undeclared in the Cython code generated from the `.pyx` files. I managed to circumvent these issues and have created a fork where the installation works:
```
sage --pip install --no-build-isolation git+https://github.com/thierry-martinez/abelfunctions@fix.264
```

However, when I tested the example from `README.md` using Sage 10.4, I encountered the following error:
```
sage: X.riemann_matrix()
[...]
TypeError: no canonical coercion from <class 'complex'> to Multivariate Polynomial Ring in x, y over Rational Field
[...]
```

**Comment by sharondavid0** [comment]
Thank you so much! The installation worked! (It should be noted that it works specifically with sagemath version 10.4 and python version 3.12.4)

**Comment by rparini** [comment]
@thierry-martinez would you be ok to submit a PR with your changes to the main abelfunctions repo?

**Comment by rparini** [comment]
@thierry-martinez I've incorporated your changes here https://github.com/abelfunctions/abelfunctions/pull/266 to fix this issue, hope that's ok. The `TypeError: no canonical coercion ...` problem you point out is captured in https://github.com/abelfunctions/abelfunctions/issues/265
